dateModified: 1565791427
email:
  fromEmail: admin@example.com
  fromName: 'Content Field Examples'
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  d6e41384-38c0-4a4b-871d-c7f0fc4eff53:
    name: Common
fields:
  2114d3c2-21f7-4cfd-bfaa-4e2021d4e21d:
    name: Content
    handle: pageContent
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: lenz\contentfield\fields\ContentField
    settings:
      compression: never
      rootSchemas:
        - 'template:_examples/fields/*'
        - 'template:_examples/schemas/*'
        - 'template:_examples/tools/*'
      useAsPageTemplate: '1'
    contentColumnType: string
    fieldGroup: d6e41384-38c0-4a4b-871d-c7f0fc4eff53
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  contentfield:
    edition: standard
    enabled: true
    schemaVersion: 1.1.3
    settings:
      cpCssFile: ''
      googleMapsApiKey: ''
      templateInlining: production
      templateIndexCache: production
      templateModificationCheck: dev
      translator: ''
      translatorSettings:
        azure:
          subscriptionKey: ''
        google:
          apiKey: ''
sections:
  96163b4a-2030-40bf-975a-0d0b4c2bb67d:
    name: Examples
    handle: examples
    type: structure
    enableVersioning: true
    propagationMethod: all
    siteSettings:
      38594be3-191b-4165-80db-d3ae47481175:
        enabledByDefault: true
        hasUrls: true
        uriFormat: '{slug}'
        template: _layouts/default
    structure:
      uid: 4b7ab101-fca5-4ea1-9774-05a3436a2530
      maxLevels: null
    entryTypes:
      34c150c2-69e5-44e9-b382-f68de6e7befe:
        name: Example
        handle: example
        hasTitleField: true
        titleLabel: Title
        titleFormat: ''
        sortOrder: 1
        fieldLayouts:
          2e79fa03-b4cc-4991-a9f5-a7391ced7553:
            tabs:
              -
                name: Content
                sortOrder: 1
                fields:
                  2114d3c2-21f7-4cfd-bfaa-4e2021d4e21d:
                    required: false
                    sortOrder: 1
      e5c5c76f-a034-482f-8bd3-56824ee34961:
        name: Group
        handle: group
        hasTitleField: true
        titleLabel: Title
        titleFormat: ''
        sortOrder: 2
siteGroups:
  ec0acea7-4384-4c7e-97fe-2b7ca7614196:
    name: 'Content Field Examples'
sites:
  38594be3-191b-4165-80db-d3ae47481175:
    baseUrl: $DEFAULT_SITE_URL
    handle: default
    hasUrls: true
    language: en-US
    name: 'Content Field Examples'
    primary: true
    siteGroup: ec0acea7-4384-4c7e-97fe-2b7ca7614196
    sortOrder: 1
system:
  edition: solo
  name: 'Content Field Examples'
  live: true
  schemaVersion: 3.2.16
  timeZone: America/Los_Angeles
users:
  requireEmailVerification: true
  allowPublicRegistration: false
  defaultGroup: null
  photoVolumeUid: null
  photoSubpath: ''
volumes:
  5ca1b5c4-e461-4fb3-813b-0db4f1de2b01:
    name: Files
    handle: files
    type: craft\volumes\Local
    hasUrls: true
    url: /files/
    settings:
      path: /Volumes/Daten/Projekte/OpenSource/craft-contentfield/examples/web/files
    sortOrder: 2
  ad09e661-973d-49d8-819a-5545a14a1494:
    name: Images
    handle: images
    type: craft\volumes\Local
    hasUrls: true
    url: /images/
    settings:
      path: /Volumes/Daten/Projekte/OpenSource/craft-contentfield/examples/web/images
    sortOrder: 1
