# This is a globally defined image tag configuration. You can use this configuration
# by passing its name to the image tag helper:
#
# ```
# {{ imageTag(asset, 'egImage') }}
# ```
egImage:
  type: config
  .class: wrapper
  .style: position:relative; {cssAspect}
  +img:
    .class: figure-img rounded img-fluid
    .srcset: $srcset
    .style: position:absolute; top:0; left:0; width:100%; height:100%

# Image tag definitions can extend each other, specify the name of the
# configuration that should be extended in the `type` attribute.
egFluidImage:
  type: egImage
  +img:
    .sizes: '(max-width: 991px) 416px, 696px'
  transforms:
    - { mode: 'crop', width: 416, height: 293 }
    - { mode: 'crop', width: 696, height: 489 }
